version: 0.2

phases:
  install:
    commands:
      - sudo apt-get install software-properties-common
      - sudo apt-add-repository universe
      - sudo apt-get update
      - sudo apt-get install python3-pip
      - npm install
      - pip3 install awscli --upgrade --user